"""initial revision

Revision ID: 17479ed22191
Revises: 49db62836d60
Create Date: 2023-02-28 15:02:40.169254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17479ed22191'
down_revision = '49db62836d60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
