"""initial revision

Revision ID: 49db62836d60
Revises: 
Create Date: 2023-02-28 15:01:27.207017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49db62836d60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
