"""initial revision

Revision ID: f325e9e02af7
Revises: 17479ed22191
Create Date: 2023-02-28 15:18:12.763219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f325e9e02af7'
down_revision = '17479ed22191'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
